dist: focal
language: minimal
services:
  - docker

branches:
  only:
    - automation

notifications:
  email:
    recipients:
    - info@mozilla.cz
    - mstanke@mozilla.cz
    on_success: change
    on_failure: always

before_script: # Get ssh key from the secret variable
 - echo "$DEPLOY_KEY" | base64 -d > deploy_key
 - chmod 600 deploy_key
 - eval `ssh-agent -s`
 - ssh-add deploy_key
 - ssh-add -L

script:
 - make update_mirror_in_docker

after_script: # Kill the ssh-agent
 - rm -f deploy_key
 - ssh-agent -k

cache:
  directories:
  - github_l10n-mozilla-central-cs
